apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: kubernetes-auth.io
      http:
        paths:
          - path: /auth(/|$)(.*)
            backend:
              serviceName: auth-service
              servicePort: 80