apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
spec:
  selector:
    matchLabels:
      run: kubernetes-auth
  replicas: 1
  template:
    metadata:
      labels:
        run: kubernetes-auth
    spec:
      containers:
        - name: file-service
          image: mikebikename/file-service:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: file-service
spec:
  selector:
    run: kubernetes-auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000