apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      run: kubernetes-auth
  replicas: 1
  template:
    metadata:
      labels:
        run: kubernetes-auth
    spec:
      containers:
        - name: auth-service
          image: mikebikename/auth-service:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    run: kubernetes-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80